/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Netomi Developer Docs",
  "tagline": "Build with the Netomi Agentic AI Platform",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser",
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    }
  },
  "themes": [
    "docusaurus-theme-openapi-docs",
    [
      "/Volumes/B/netomi/assessment/assessment-net/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "docsRouteBasePath": [
          "/docs",
          "/api-reference",
          "/sdks",
          "/help-center"
        ],
        "indexBlog": false,
        "language": [
          "en"
        ]
      }
    ]
  ],
  "url": "https://your-netlify-url.netlify.app",
  "baseUrl": "/",
  "organizationName": "HaresshTechWr",
  "projectName": "assessment-net",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "docs",
          "lastVersion": "1.0.0",
          "versions": {
            "current": {
              "label": "Next 🚧",
              "path": "next"
            },
            "1.0.0": {
              "label": "1.0.0",
              "path": "1.0.0"
            }
          },
          "editUrl": "https://github.com/HaresshTechWr/assessment-net/tree/main/"
        },
        "blog": {
          "path": "blog",
          "routeBasePath": "changelog",
          "blogTitle": "Changelog",
          "blogDescription": "Product updates and release notes",
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/HaresshTechWr/assessment-net/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "sdks",
        "path": "sdks",
        "routeBasePath": "sdks",
        "sidebarPath": "./sidebarsSdks.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "api-reference",
        "path": "api-reference",
        "routeBasePath": "api-reference",
        "sidebarPath": "./sidebarsApi.js",
        "docItemComponent": "@theme/ApiItem"
      }
    ],
    [
      "docusaurus-plugin-openapi-docs",
      {
        "id": "openapi",
        "docsPluginId": "api-reference",
        "config": {
          "netomi": {
            "specPath": "openapi.yaml",
            "outputDir": "api-reference",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            }
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "help-center",
        "path": "help-center",
        "routeBasePath": "help-center",
        "sidebarPath": "./sidebarsHelp.js"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Netomi",
      "logo": {
        "alt": "Netomi Docs Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "introduction",
          "position": "left",
          "label": "Documentation"
        },
        {
          "type": "doc",
          "docId": "overview",
          "docsPluginId": "sdks",
          "position": "left",
          "label": "SDKs"
        },
        {
          "type": "doc",
          "docId": "overview",
          "docsPluginId": "api-reference",
          "position": "left",
          "label": "API Reference"
        },
        {
          "label": "More",
          "position": "left",
          "items": [
            {
              "to": "/changelog",
              "label": "Changelog"
            },
            {
              "to": "/help-center/faq",
              "label": "Help Center"
            }
          ]
        },
        {
          "type": "docsVersionDropdown",
          "docsPluginId": "default",
          "position": "right",
          "className": "netomi-version-dropdown",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "https://app.netomi.com",
          "label": "Sign in",
          "position": "right",
          "className": "navbar-signin-button"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Product",
          "items": [
            {
              "label": "Documentation",
              "to": "/docs/introduction"
            },
            {
              "label": "SDKs",
              "to": "/sdks/overview"
            },
            {
              "label": "API Reference",
              "to": "/api-reference/overview"
            },
            {
              "label": "Changelog",
              "to": "/changelog"
            }
          ]
        },
        {
          "title": "Support",
          "items": [
            {
              "label": "Help Center",
              "to": "/help-center/faq"
            },
            {
              "label": "Troubleshooting",
              "to": "/help-center/troubleshooting"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "Sign in",
              "href": "https://app.netomi.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Netomi. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
